const books = [
  {
    ID: 1,
    Title: "To Kill a Mockingbird",
    Description: "A novel about the serious issues of rape and racial inequality.",
    Author: "Harper Lee",
    Year: 1960,
    ImageURI: "https://example.com/to-kill-a-mockingbird.jpg",
    Borrows: 120,
  },
  {
    ID: 2,
    Title: "1984",
    Description: "A dystopian novel set in a totalitarian society under constant surveillance.",
    Author: "George Orwell",
    Year: 1949,
    ImageURI: "https://example.com/1984.jpg",
    Borrows: 95,
  },
  {
    ID: 3,
    Title: "The Great Gatsby",
    Description: "A novel about the decline of the American Dream in the 1920s.",
    Author: "F. Scott Fitzgerald",
    Year: 1925,
    ImageURI: "https://example.com/the-great-gatsby.jpg",
    Borrows: 85,
  },
  {
    ID: 4,
    Title: "Moby Dick",
    Description: "A whaling ship's journey and its captain's obsession with revenge against a white whale.",
    Author: "Herman Melville",
    Year: 1851,
    ImageURI: "https://example.com/moby-dick.jpg",
    Borrows: 45,
  },
  {
    ID: 5,
    Title: "Pride and Prejudice",
    Description: "A romantic novel that explores the issues of marriage, money, and love.",
    Author: "Jane Austen",
    Year: 1813,
    ImageURI: "https://example.com/pride-and-prejudice.jpg",
    Borrows: 110,
  },
  {
    ID: 6,
    Title: "The Catcher in the Rye",
    Description: "A story about a young man's struggles with growing up and finding his place in the world.",
    Author: "J.D. Salinger",
    Year: 1951,
    ImageURI: "https://example.com/the-catcher-in-the-rye.jpg",
    Borrows: 77,
  },
  {
    ID: 7,
    Title: "Brave New World",
    Description: "A dystopian novel set in a futuristic society focused on technological control.",
    Author: "Aldous Huxley",
    Year: 1932,
    ImageURI: "https://example.com/brave-new-world.jpg",
    Borrows: 68,
  },
  {
    ID: 8,
    Title: "War and Peace",
    Description: "A historical novel about the French invasion of Russia and its impact on aristocratic families.",
    Author: "Leo Tolstoy",
    Year: 1869,
    ImageURI: "https://example.com/war-and-peace.jpg",
    Borrows: 34,
  },
  {
    ID: 9,
    Title: "The Hobbit",
    Description: "A fantasy novel that follows the adventure of Bilbo Baggins in Middle-earth.",
    Author: "J.R.R. Tolkien",
    Year: 1937,
    ImageURI: "https://example.com/the-hobbit.jpg",
    Borrows: 150,
  },
  {
    ID: 10,
    Title: "Crime and Punishment",
    Description: "A psychological novel about the moral dilemmas of a young man who commits a crime.",
    Author: "Fyodor Dostoevsky",
    Year: 1866,
    ImageURI: "https://example.com/crime-and-punishment.jpg",
    Borrows: 58,
  },
];

export default books;
